# Generated by Django 5.1.7 on 2025-04-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'Regular User'), ('seller', 'Seller')], default='user', max_length=10),
        ),
    ]
