# Generated by Django 5.1.7 on 2025-04-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Electronicos', 'ELECTRONICOS'), ('Juegos', 'JUEGOS')], max_length=15, null=True),
        ),
    ]
